name: Python Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları checkout et
      uses: actions/checkout@v3

    - name: Python ortamını kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # İstersen başka bir versiyon seçebilirsin

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testleri çalıştır
      run: |
        python tests/test_question.py